### ISSUE TITLE
What sigma do I need to use?

### ISSUE THREAD

**Issue by timofeytkachenko** [ovidijusku/msprt#2]
I have run the AB test and I'm logging the outcomes at every step, then I have two samples, control, and treatment, what sigma I should pick in my case (conversion)?

I tried  (sample_A.std() + sample_B.std())/2 but maybe you have some reccomendations

**Comment by ovidijusku** [comment]
> I have run the AB test and I'm logging the outcomes at every step, then I have two samples, control, and treatment, what sigma I should pick in my case (conversion)?
> 
> I tried  (sample_A.std() + sample_B.std())/2 but maybe you have some reccomendations

Standard deviation should not be calculated as arithmetic mean. Here is the formula that you should calculate sigma:

![FormulaImage.png](https://github.com/ovidijusku/msprt/assets/70970616/9b7aa925-7937-4c73-8821-cdec392cb9d7)

**Comment by timofeytkachenko** [comment]
@ovidijusku thank you

And I have one more question about theta, as I understand theta it is our absolute mde, am I right?

**Comment by ovidijusku** [comment]
> @ovidijusku thank you
> 
> And I have one more question about theta, as I understand theta it is our absolute mde, am I right?

Not really, it is a threshold value used to tune the decision rule. It acts more dynamically based on the experiment state than pre-determined MDE.

**Comment by timofeytkachenko** [comment]
I found that in any case your code returns "Accept H0" or "Accept H1" in comparison with simple SPRT which can return "Continue" and as I understand when your code returns  "Accept H0" and n_rejection == sample _size it means "Continue" :)
