### ISSUE TITLE
mSPRT when our samples have different size

### ISSUE THREAD

**Issue by timofeytkachenko** [ovidijusku/msprt#3]
In a real AB-test scenario we can have different numbers of observations per day, how can we use mSPRT in a such case?

**Comment by ovidijusku** [comment]
Imagine that we have 150 observations in control and 155 observations in the test group. So by taking the first 150 observations from both groups, you would equalize samples. With a larger number of observations, the difference between groups should be negligibly small, but the logic remains the same.
